const { chromium } = require('playwright');
(async()=>{
  const browser=await chromium.launch({headless:true});
  const page=await browser.newPage({viewport:{width:1440,height:900}, recordVideo:{dir:'/mnt/data/v32work/pwvideo'}});
  const errors=[]; const logs=[];
  page.on('console',m=>{if(m.type()==='error') errors.push(m.text()); logs.push(m.text());});
  page.on('pageerror',e=>errors.push('PAGEERROR: '+e.message));
  await page.goto('http://127.0.0.1:8765/',{waitUntil:'networkidle'});
  await page.waitForTimeout(2100);
  console.log('home title',await page.title());
  console.log('active',await page.locator('.view.active').getAttribute('id'));
  await page.locator('[data-go="preview"]').first().click();
  await page.waitForTimeout(300);
  console.log('preview active',await page.locator('.view.active').getAttribute('id'));
  await page.locator('#playDemo').click();
  await page.waitForTimeout(700);
  console.log('video paused?',await page.locator('#simVideo').evaluate(v=>v.paused),'current',await page.locator('#simVideo').evaluate(v=>v.currentTime));
  await page.locator('.simBand[data-band="valued"]').click();
  console.log('moment',await page.locator('#moment').inputValue());
  await page.locator('#playDemo').click();
  await page.waitForTimeout(800);
  console.log('overlay opacity',await page.locator('#ovVisual').evaluate(el=>getComputedStyle(el).opacity));
  await page.locator('[data-go="request"]').first().click();
  await page.waitForTimeout(200);
  console.log('request active',await page.locator('.view.active').getAttribute('id'));
  console.log('errors',errors);
  await page.screenshot({path:'/mnt/data/v32work/browser_home.png',fullPage:true});
  await browser.close();
})();
