'use client';
import { useEffect,useMemo,useState } from 'react';
import { BadgeDollarSign,X,RefreshCw } from 'lucide-react';
import { supabase } from '../../lib/supabase';
export default function ControlSponsors(){const[open,setOpen]=useState(false),[rows,setRows]=useState([]),[msg,setMsg]=useState('');
 useEffect(()=>{const nav=document.querySelector('.controlSide nav');if(!nav||document.getElementById('sponsors-control-entry'))return;const b=document.createElement('button');b.id='sponsors-control-entry';b.innerHTML='<span style="font-size:18px">◆</span><span>Patrocinadores</span>';b.onclick=()=>setOpen(true);nav.appendChild(b);return()=>b.remove()},[]);
 async function load(){const{data,error}=await supabase.from('hocco_patrocinios').select('*').order('created_at',{ascending:false}).limit(300);if(error)setMsg(error.message);else setRows(data||[])}
 useEffect(()=>{if(open)load()},[open]);
 async function act(r,status){let q=r.quadro||1;if(status==='ATIVO'){const raw=prompt('Quadro (1 a 4):',String(q));if(!raw)return;q=Number(raw)}const reason=prompt('Observação/motivo:','Operação HOCCO Control')||'Operação HOCCO Control';const{error}=await supabase.rpc('admin_set_patrocinio',{p_id:r.id,p_status:status,p_quadro:q,p_posicao:null,p_reason:reason});setMsg(error?(error.message.includes('board_full')?'Este quadro já possui 4 marcas ativas.':error.message):'Patrocínio atualizado.');load()}
 const active=rows.filter(r=>r.status==='ATIVO'&&new Date(r.fim_at)>new Date()),gross=active.reduce((s,r)=>s+Number(r.valor||0),0),imps=rows.reduce((s,r)=>s+Number(r.impressoes||0),0),clicks=rows.reduce((s,r)=>s+Number(r.cliques||0),0);
 if(!open)return null;return <div style={S.overlay}><section style={S.panel}><header style={S.head}><div><small>HOCCO CONTROL</small><h1 style={{margin:'3px 0'}}>Marcas Permanentes</h1><p style={S.muted}>16 vagas · 4 quadros · 4 marcas por quadro · R$ 49,90 / 7 dias</p></div><button style={S.close} onClick={()=>setOpen(false)}><X/></button></header><div style={S.stats}><Stat t="Ocupadas" v={`${active.length}/16`}/><Stat t="Livres" v={16-active.length}/><Stat t="Receita ativa" v={gross.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}/><Stat t="CTR" v={`${imps?((clicks/imps)*100).toFixed(2):'0.00'}%`}/></div>{msg&&<div style={S.msg}>{msg}</div>}<button style={S.refresh} onClick={load}><RefreshCw/> Atualizar</button><div style={S.boards}>{[1,2,3,4].map(q=><article style={S.board} key={q}><h3>Quadro {q} <span>{active.filter(r=>r.quadro===q).length}/4</span></h3>{active.filter(r=>r.quadro===q).map(r=><Sponsor r={r} key={r.id} act={act}/>)}{!active.some(r=>r.quadro===q)&&<p style={S.muted}>Nenhuma marca ativa.</p>}</article>)}</div><h2>Solicitações e histórico</h2><div style={S.list}>{rows.map(r=><Sponsor r={r} key={r.id} act={act} full/>)}</div></section></div>}
function Sponsor({r,act,full}){return <div style={S.row}><img src={r.logo_url} alt="" style={{width:44,height:44,objectFit:'contain'}}/><div style={{flex:1}}><b>{r.nome_fantasia}</b><small style={{display:'block',color:'#718198'}}>{r.payment_reference} · {r.status}{r.fim_at?` · até ${new Date(r.fim_at).toLocaleDateString('pt-BR')}`:''}</small>{full&&<small>{r.impressoes} impressões · {r.cliques} cliques</small>}</div><div style={{display:'flex',gap:5,flexWrap:'wrap'}}>{r.status!=='ATIVO'&&<button style={S.action} onClick={()=>act(r,'ATIVO')}>ATIVAR</button>}{r.status==='ATIVO'&&<button style={S.action} onClick={()=>act(r,'ENCERRADO')}>ENCERRAR</button>}{['SOLICITADO','EM ANÁLISE'].includes(r.status)&&<button style={S.action} onClick={()=>act(r,'APROVADO')}>APROVAR</button>}{!['RECUSADO','ENCERRADO','CANCELADO'].includes(r.status)&&<button style={S.danger} onClick={()=>act(r,'RECUSADO')}>RECUSAR</button>}</div></div>}
function Stat({t,v}){return <div style={S.stat}><small>{t}</small><b>{v}</b></div>}
const S={overlay:{position:'fixed',inset:0,zIndex:30000,background:'rgba(4,15,34,.7)',padding:14,overflow:'auto'},panel:{width:'min(1100px,100%)',margin:'20px auto',background:'#f5f8fc',borderRadius:24,padding:20,color:'#10213b'},head:{display:'flex',justifyContent:'space-between',gap:12},close:{border:0,background:'#fff',borderRadius:12,width:44,height:44},muted:{color:'#718198'},stats:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:10,margin:'16px 0'},stat:{background:'#fff',padding:15,borderRadius:16,border:'1px solid #e1e8f0',display:'grid',gap:5},boards:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:10},board:{background:'#fff',padding:14,borderRadius:18,border:'1px solid #e1e8f0'},row:{display:'flex',alignItems:'center',gap:10,padding:'10px 0',borderBottom:'1px solid #e6ebf2',flexWrap:'wrap'},list:{background:'#fff',padding:'0 14px',borderRadius:18},action:{border:0,borderRadius:9,padding:'8px 9px',background:'#075eea',color:'#fff',fontWeight:800,fontSize:10},danger:{border:0,borderRadius:9,padding:'8px 9px',background:'#feecef',color:'#b42336',fontWeight:800,fontSize:10},refresh:{border:0,background:'#fff',padding:10,borderRadius:10,display:'flex',gap:6,marginBottom:10},msg:{padding:10,background:'#eef5ff',borderRadius:10}};