'use client';
import { useEffect,useState } from 'react';
import { ArrowLeft,CheckCircle2,ExternalLink,Image as ImageIcon,RefreshCw } from 'lucide-react';
import { supabase } from '../../lib/supabase';
import { brl } from '../../lib/config';

const PRICE=49.90;
const DESTINOS=['whatsapp','instagram','facebook','youtube','tiktok','site'];
export default function PatrocinarApp(){
 const [user,setUser]=useState(null),[rows,setRows]=useState([]),[logo,setLogo]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{supabase.auth.getUser().then(({data})=>{if(!data.user)location.replace('/');else{setUser(data.user);load(data.user.id)}})},[]);
 async function load(uid=user?.id){if(!uid)return;const{data}=await supabase.from('hocco_patrocinios').select('*').eq('user_id',uid).order('created_at',{ascending:false});setRows(data||[])}
 async function upload(e){const f=e.target.files?.[0];if(!f||!user)return;if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>4*1024*1024)return setMsg('Use PNG, JPG ou WEBP de até 4 MB.');setBusy(true);const path=`${user.id}/sponsors/${crypto.randomUUID()}.${f.type==='image/png'?'png':'webp'}`;const{error}=await supabase.storage.from('impulsionadores-avatars').upload(path,f,{contentType:f.type});if(error){setMsg('Não foi possível enviar o logo.');setBusy(false);return}const{data}=supabase.storage.from('impulsionadores-avatars').getPublicUrl(path);setLogo(data.publicUrl);setBusy(false);}
 async function submit(e){e.preventDefault();if(!logo)return setMsg('Envie o logo da empresa.');const f=new FormData(e.currentTarget);const url=String(f.get('destino_url')||'').trim();if(!/^https:\/\//i.test(url))return setMsg('Informe o link completo começando por https://');setBusy(true);const{error}=await supabase.from('hocco_patrocinios').insert({user_id:user.id,nome_fantasia:String(f.get('nome_fantasia')).trim(),logo_url:logo,destino_tipo:f.get('destino_tipo'),destino_url:url,quadro:Number(f.get('quadro')),valor:PRICE,status:'SOLICITADO'});setBusy(false);if(error)return setMsg('Não foi possível criar o patrocínio.');setLogo('');e.currentTarget.reset();setMsg('Solicitação criada. Faça o pagamento e informe à HOCCO.');load();}
 async function paid(id){const{error}=await supabase.rpc('informar_pagamento_patrocinio',{p_id:id});setMsg(error?'Não foi possível informar o pagamento.':'Pagamento informado. A HOCCO fará a conferência.');load()}
 async function renew(id){const{error}=await supabase.rpc('renovar_patrocinio',{p_id:id});setMsg(error?'Não foi possível renovar agora.':'Renovação aberta por mais 7 dias.');load()}
 const active=rows.find(r=>r.status==='ATIVO'&&new Date(r.fim_at)>new Date());
 return <main style={S.page}><header style={S.header}><button style={S.icon} onClick={()=>location.href='/empresa'}><ArrowLeft/></button><b>HYPE</b><span style={S.pill}>MARCAS PERMANENTES</span></header><section style={S.shell}>
 <div><small>PATROCÍNIO DO APP</small><h1 style={S.h1}>{active?'Meu patrocínio':'Patrocinar o app'}</h1><p style={S.p}>Sua marca permanece por 7 dias em uma área institucional do Hype. São 4 quadros com 4 marcas cada. O patrocínio nunca altera votos, ranking, HC, missões ou resultado do Hype.</p></div>
 {active&&<article style={S.active}><div><small>ATIVO ATÉ {new Date(active.fim_at).toLocaleDateString('pt-BR')}</small><h2>{active.nome_fantasia}</h2><p>Quadro {active.quadro} · posição rotativa · {active.impressoes} impressões · {active.cliques} cliques · CTR {active.impressoes?((active.cliques/active.impressoes)*100).toFixed(2):'0.00'}%</p></div><button style={S.secondary} onClick={()=>renew(active.id)}><RefreshCw/> Renovar 7 dias</button></article>}
 <div style={S.rules}><b>R$ 49,90 · 7 dias</b><span>16 vagas totais</span><span>Somente logo + link direto</span><span>Posições rotativas</span></div>
 <form onSubmit={submit} style={S.form}><label>Nome fantasia<input name="nome_fantasia" required/></label><label>Quadro<select name="quadro" defaultValue="1"><option value="1">Quadro 1 · Home</option><option value="2">Quadro 2 · Hype ao vivo</option><option value="3">Quadro 3 · Explorar / Benefícios</option><option value="4">Quadro 4 · Parceiros</option></select></label><label>Destino<select name="destino_tipo">{DESTINOS.map(x=><option key={x}>{x}</option>)}</select></label><label>Link do perfil<input name="destino_url" type="url" placeholder="https://..." required/></label><label style={S.upload}><input type="file" accept="image/png,image/jpeg,image/webp" onChange={upload}/>{logo?<img src={logo} alt="Logo" style={{maxWidth:120,maxHeight:70}}/>:<><ImageIcon/><b>Enviar logo</b></>}</label><label style={S.check}><input type="checkbox" required/> Entendo que este produto compra exposição institucional e não influencia a competição do Hype.</label><button style={S.primary} disabled={busy}>{busy?'PROCESSANDO...':`SOLICITAR · ${brl(PRICE)} / 7 DIAS`}</button></form>
 {msg&&<div style={S.msg}>{msg}</div>}
 {!!rows.length&&<section><h2>Meus patrocínios</h2>{rows.map(r=><article key={r.id} style={S.row}><img src={r.logo_url} alt="" style={{width:48,height:48,objectFit:'contain'}}/><div style={{flex:1}}><b>{r.nome_fantasia}</b><small style={{display:'block'}}>{r.payment_reference} · {r.status} · Quadro {r.quadro}</small></div><strong>{brl(r.valor)}</strong>{['SOLICITADO','AGUARDANDO PAGAMENTO'].includes(r.status)&&<button style={S.secondary} onClick={()=>paid(r.id)}><CheckCircle2/> Já fiz o PIX</button>}{r.status==='ENCERRADO'&&<button style={S.secondary} onClick={()=>renew(r.id)}><RefreshCw/> Renovar</button>}</article>)}</section>}
 <a href="/empresa" style={S.back}><ExternalLink/> Voltar à área empresarial</a></section></main>}
const S={page:{minHeight:'100vh',background:'#f5f8fc',color:'#10213b',fontFamily:'system-ui'},header:{height:68,display:'flex',alignItems:'center',gap:14,padding:'0 18px',background:'#fff',borderBottom:'1px solid #e4eaf2'},icon:{border:0,background:'transparent'},pill:{marginLeft:'auto',fontSize:11,fontWeight:900,color:'#075eea'},shell:{width:'min(760px,calc(100% - 28px))',margin:'0 auto',padding:'32px 0 60px'},h1:{fontSize:'clamp(30px,7vw,48px)',margin:'5px 0'},p:{color:'#63738a',lineHeight:1.6},active:{background:'#071c3d',color:'#fff',borderRadius:22,padding:20,display:'flex',gap:15,justifyContent:'space-between',alignItems:'center'},rules:{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(140px,1fr))',gap:8,margin:'18px 0',padding:16,background:'#fff',borderRadius:18,border:'1px solid #e1e8f0'},form:{display:'grid',gap:13,background:'#fff',padding:20,borderRadius:22,border:'1px solid #e1e8f0'},upload:{minHeight:110,border:'1px dashed #9aabc0',borderRadius:16,display:'grid',placeItems:'center',cursor:'pointer'},check:{fontSize:12,color:'#53657d'},primary:{border:0,borderRadius:14,padding:16,background:'#075eea',color:'#fff',fontWeight:900},secondary:{border:'1px solid #d5deea',borderRadius:12,padding:'10px 12px',background:'#fff',fontWeight:800,display:'inline-flex',gap:6,alignItems:'center'},msg:{margin:'14px 0',padding:13,background:'#eef5ff',borderRadius:13},row:{display:'flex',alignItems:'center',gap:12,padding:13,background:'#fff',borderBottom:'1px solid #e6ebf2',flexWrap:'wrap'},back:{marginTop:20,display:'inline-flex',gap:7,color:'#075eea',fontWeight:800,textDecoration:'none'}};