'use client';
import {useEffect,useMemo,useState} from 'react';
import {createClient} from '@supabase/supabase-js';
import {Home,Target,HeartHandshake,Users,User,Bolt,CheckCircle2,Trophy,Play,ShieldCheck,Copy,Building2,MapPin,Landmark,LogOut,Camera,Download,ExternalLink,Mail,Lock,Chrome} from 'lucide-react';
import {QRCodeSVG} from 'qrcode.react';
const SUPABASE_URL='https://vebqvedmhfaebvdantiu.supabase.co';
const SUPABASE_KEY='sb_publishable_4qUcXYXNFDUc6UAw_nvpDw_M-9w3vuz';
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY);
const PIX_KEY='c9316176-6f92-413e-9209-63ae6f661ba9',RECEIVER='Alex Sandro Soares Fernandes';
const YOUTUBE='https://www.youtube.com/@hoccpov',TIKTOK='https://www.tiktok.com/@hoccobrasil';
const missions=[['Motor Ligado','Impulsione a HOCCO 100 vezes.',100],['Presença','Marque sua presença hoje.',30],['HOCCO Hoje','Veja o conteúdo indicado do dia.',50],['Voz HOCCO','Responda à pergunta do dia.',70],['Escolha','Participe da votação HOCCO.',50],['Explore','Conheça um projeto HOCCO.',40],['Impulso Completo','Complete seus impulsos do dia.',100],['Descubra','Encontre o destaque do dia.',80],['Sequência','Mantenha sua sequência ativa.',60],['Comunidade','Participe da meta coletiva.',60]];
function tlv(id,v){return id+String(v.length).padStart(2,'0')+v}function crc(s){let x=0xffff;for(let i=0;i<s.length;i++){x^=s.charCodeAt(i)<<8;for(let j=0;j<8;j++)x=(x&0x8000)?((x<<1)^0x1021)&0xffff:(x<<1)&0xffff}return x.toString(16).toUpperCase().padStart(4,'0')}function pixPayload(a){const mai=tlv('00','BR.GOV.BCB.PIX')+tlv('01',PIX_KEY);let s=tlv('00','01')+tlv('26',mai)+tlv('52','0000')+tlv('53','986')+tlv('54',Number(a).toFixed(2))+tlv('58','BR')+tlv('59','ALEX SANDRO SOARES FERN')+tlv('60','BAURU')+tlv('62',tlv('05','***'))+'6304';return s+crc(s)}
export default function App(){const [session,setSession]=useState(null),[loading,setLoading]=useState(true),[authMode,setAuthMode]=useState('signup'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[authMsg,setAuthMsg]=useState(''),[profile,setProfile]=useState(null),[tab,setTab]=useState('Início'),[today,setToday]=useState(0),[amount,setAmount]=useState(10),[paid,setPaid]=useState(false),[installPrompt,setInstallPrompt]=useState(null),[editing,setEditing]=useState(false),[community,setCommunity]=useState([]);
useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));const h=e=>{e.preventDefault();setInstallPrompt(e)};window.addEventListener('beforeinstallprompt',h);return()=>{subscription.unsubscribe();window.removeEventListener('beforeinstallprompt',h)}},[]);
useEffect(()=>{if(!session?.user)return;loadProfile();loadToday();loadCommunity()},[session?.user?.id]);
async function loadProfile(){const u=session.user;let {data}=await supabase.from('impulsionadores_perfis').select('*').eq('user_id',u.id).maybeSingle();if(!data){const display=u.user_metadata?.full_name||u.user_metadata?.name||u.email?.split('@')[0]||'Novo membro';const avatar=u.user_metadata?.avatar_url||null;const r=await supabase.from('impulsionadores_perfis').insert({user_id:u.id,nome_publico:display,avatar_url:avatar}).select().single();data=r.data}setProfile(data)}
async function loadToday(){const start=new Date();start.setHours(0,0,0,0);const {count}=await supabase.from('impulsionadores_impulsos').select('*',{count:'exact',head:true}).gte('created_at',start.toISOString());setToday(Math.min(100,count||0))}
async function loadCommunity(){const {data}=await supabase.from('impulsionadores_perfis').select('user_id,nome_publico,avatar_url,xp,nivel').order('xp',{ascending:false}).limit(20);setCommunity(data||[])}
async function submitAuth(e){e.preventDefault();setAuthMsg('');if(password.length<6){setAuthMsg('Use uma senha com pelo menos 6 caracteres.');return}if(authMode==='signup'){if(name.trim().length<2){setAuthMsg('Informe seu nome ou apelido.');return}const {data,error}=await supabase.auth.signUp({email,password,options:{data:{full_name:name.trim()},emailRedirectTo:location.origin}});if(error)setAuthMsg(error.message);else if(data.session)setSession(data.session);else setAuthMsg('Cadastro criado. Confirme seu e-mail para entrar.')}else{const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)setAuthMsg('E-mail ou senha inválidos.');else setSession(data.session)}}
async function google(){setAuthMsg('');const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin}});if(error)setAuthMsg('Google ainda precisa ser habilitado na configuração de acesso.')}
async function impulse(){if(today>=100)return;const {data,error}=await supabase.rpc('registrar_impulso');if(error){if(error.message.includes('rate_limited'))return;setAuthMsg('Não foi possível registrar este impulso.');return}setToday(data.progresso);if(data.concluida)await loadProfile()}
async function uploadAvatar(e){const f=e.target.files?.[0];if(!f||!session)return;if(f.size>5*1024*1024){alert('A foto deve ter até 5 MB.');return}const ext=(f.name.split('.').pop()||'jpg').toLowerCase();const path=`${session.user.id}/avatar.${ext}`;const {error}=await supabase.storage.from('impulsionadores-avatars').upload(path,f,{upsert:true});if(error){alert('Não foi possível enviar a foto.');return}const {data}=supabase.storage.from('impulsionadores-avatars').getPublicUrl(path);await supabase.from('impulsionadores_perfis').update({avatar_url:data.publicUrl+'?v='+Date.now(),updated_at:new Date().toISOString()}).eq('user_id',session.user.id);await loadProfile()}
async function saveProfile(e){e.preventDefault();const fd=new FormData(e.currentTarget);await supabase.from('impulsionadores_perfis').update({nome_publico:String(fd.get('nome')).trim().slice(0,40),username:String(fd.get('username')).trim().replace(/^@/,'').slice(0,30)||null,bio:String(fd.get('bio')).trim().slice(0,160)||null,updated_at:new Date().toISOString()}).eq('user_id',session.user.id);setEditing(false);await loadProfile()}
async function install(){if(installPrompt){installPrompt.prompt();await installPrompt.userChoice;setInstallPrompt(null)}else alert('No celular, abra o menu do navegador e escolha “Adicionar à tela inicial” ou “Instalar app”.')}
if(loading)return <div className="splash"><b>HOCCO</b><span>Carregando comunidade...</span></div>;
if(!session)return <Auth mode={authMode} setMode={setAuthMode} email={email} setEmail={setEmail} password={password} setPassword={setPassword} name={name} setName={setName} submit={submitAuth} google={google} msg={authMsg} install={install}/>;
const p=profile||{nome_publico:'Membro',xp:0,nivel:1,impulsos:0,missoes_concluidas:0,ciclos:0,selos:0};const next=p.nivel*500,pct=Math.min(100,(p.xp%500)/500*100),payload=useMemo(()=>pixPayload(amount),[amount]);const nav=[['Início',Home],['Missões',Target],['Impulsionar',HeartHandshake],['Comunidade',Users],['Perfil',User]];
return <main><header><b className="logo">HOCCO</b><span className="pill">IMPULSIONADORES</span><button className="installMini" onClick={install}><Download/> Instalar</button><button className="avatarBtn" onClick={()=>setTab('Perfil')}>{p.avatar_url?<img src={p.avatar_url} alt="Perfil"/>:<span>{p.nome_publico[0]?.toUpperCase()}</span>}</button></header><section className="shell">
{tab==='Início'&&<><div className="hello"><div><small>COMUNIDADE HOCCO</small><h1>Olá, {p.nome_publico.split(' ')[0]}.</h1><p>Nível {p.nivel} · Impulsionador</p></div><div className="level">NÍVEL<br/><strong>{p.nivel}</strong></div></div><div className="progress"><div style={{width:pct+'%'}}/></div><div className="xp"><b>{p.xp.toLocaleString('pt-BR')} XP</b><span>{500-(p.xp%500)} XP para o próximo nível</span></div><article className="hero"><div className="eyebrow">MISSÃO DE HOJE</div><h2>Motor Ligado</h2><p>Impulsione a HOCCO 100 vezes.</p><div className="missionline"><span>{today}/100</span><div><i style={{width:today+'%'}}/></div></div><button onClick={impulse} disabled={today>=100}><Bolt/>{today>=100?'MISSÃO CONCLUÍDA':'IMPULSIONAR'}</button><small>+100 XP ao completar</small></article><Social/><button className="installCard" onClick={install}><Download/><div><b>Baixar HOCCO no celular</b><span>Instale o app na tela inicial e entre sempre na sua conta.</span></div></button></>}
{tab==='Missões'&&<><Title small="CICLO HOCCO" title="Suas missões" text="Uma missão por dia. Seu progresso fica salvo na sua conta."/><div className="list">{missions.map((m,i)=><div className="row" key={m[0]}><span className="ico">{i===0&&today>=100?<CheckCircle2/>:<Target/>}</span><div><b>{m[0]}</b><small>{m[1]}</small></div><em>+{m[2]} XP</em></div>)}</div></>}
{tab==='Impulsionar'&&<><Title small="APOIO À PRODUÇÃO" title="Impulsionar a HOCCO" text="Pagamento único via PIX. Sem assinatura e sem promessa de retorno financeiro."/>{!paid?<><div className="amounts">{[3,5,10,25,50,100].map(v=><button className={amount===v?'selected':''} onClick={()=>setAmount(v)} key={v}>R$ {v}</button>)}</div><label>Outro valor<input type="number" min="3" value={amount} onChange={e=>setAmount(Math.max(3,Number(e.target.value)||3))}/></label><div className="summary"><span>Valor da impulsão</span><strong>R$ {Number(amount).toFixed(2).replace('.',',')}</strong><p>O apoio financeiro é separado do XP e não compra posição no ranking.</p></div><button className="primary" onClick={()=>setPaid(true)}>GERAR PAGAMENTO PIX</button></>:<Payment amount={amount} payload={payload} back={()=>setPaid(false)}/>}</>}
{tab==='Comunidade'&&<><Title small="MEMBROS" title="Comunidade" text="Ranking por participação e XP, nunca pelo valor financeiro apoiado."/><div className="rank">{community.map((r,i)=><div className="row" key={r.user_id}><span className="place">{i+1}</span>{r.avatar_url?<img className="miniAvatar" src={r.avatar_url} alt=""/>:<span className="miniAvatar fallback">{r.nome_publico[0]}</span>}<div><b>{r.nome_publico}{r.user_id===session.user.id?' (você)':''}</b><small>Nível {r.nivel} · {r.xp.toLocaleString('pt-BR')} XP</small></div></div>)}</div><Social/></>}
{tab==='Perfil'&&<><div className="profile"><label className="photo">{p.avatar_url?<img src={p.avatar_url} alt="Foto de perfil"/>:<span>{p.nome_publico[0]}</span>}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={uploadAvatar}/><i><Camera/></i></label><h1>{p.nome_publico}</h1><p>{p.username?'@'+p.username:session.user.email}</p><b>NÍVEL {p.nivel} · IMPULSIONADOR</b></div><div className="stats"><div><strong>{p.impulsos}</strong><span>Impulsos</span></div><div><strong>{p.missoes_concluidas}</strong><span>Missões</span></div><div><strong>{p.ciclos}</strong><span>Ciclos</span></div><div><strong>{p.selos}</strong><span>Selos</span></div></div>{editing?<form className="edit" onSubmit={saveProfile}><label>Nome público<input name="nome" defaultValue={p.nome_publico} required minLength="2"/></label><label>@ na comunidade<input name="username" defaultValue={p.username||''}/></label><label>Sobre você<textarea name="bio" defaultValue={p.bio||''} maxLength="160"/></label><button className="primary">SALVAR PERFIL</button></form>:<button className="outline" onClick={()=>setEditing(true)}>EDITAR PERFIL</button>}<Social/><button className="outline" onClick={install}><Download/> INSTALAR APP</button><button className="logout" onClick={()=>supabase.auth.signOut()}><LogOut/> Sair da conta</button></>}
</section><nav>{nav.map(([n,I])=><button className={tab===n?'active':''} onClick={()=>setTab(n)} key={n}><I/><span>{n}</span></button>)}</nav></main>}
function Auth({mode,setMode,email,setEmail,password,setPassword,name,setName,submit,google,msg,install}){return <div className="auth"><div className="authBrand"><b>HOCCO</b><span>IMPULSIONADORES</span></div><div className="authCard"><small>COMUNIDADE OFICIAL</small><h1>{mode==='signup'?'Faça parte da HOCCO':'Bem-vindo de volta'}</h1><p>Sua conta guarda seu perfil, XP, missões, impulsos e trajetória em qualquer celular ou computador.</p><button className="google" onClick={google}><Chrome/> Continuar com Google</button><div className="or"><span/>ou<span/></div><form onSubmit={submit}>{mode==='signup'&&<label>Nome ou apelido<input value={name} onChange={e=>setName(e.target.value)} placeholder="Como você quer aparecer" required/></label>}<label>E-mail<div className="inputIcon"><Mail/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="voce@email.com" required/></div></label><label>Senha<div className="inputIcon"><Lock/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Mínimo 6 caracteres" required minLength="6"/></div></label>{msg&&<div className="authMsg">{msg}</div>}<button className="primary">{mode==='signup'?'CRIAR MINHA CONTA':'ENTRAR'}</button></form><button className="switch" onClick={()=>setMode(mode==='signup'?'login':'signup')}>{mode==='signup'?'Já tenho uma conta · Entrar':'Ainda não sou membro · Criar conta'}</button></div><button className="downloadAuth" onClick={install}><Download/> Baixar app no celular</button><Social/></div>}
function Social(){return <section className="social"><small>HOCCO NAS REDES</small><div><a href={YOUTUBE} target="_blank" rel="noreferrer"><Play/> YouTube · @hoccpov <ExternalLink/></a><a href={TIKTOK} target="_blank" rel="noreferrer"><Bolt/> TikTok · @Hoccobrasil <ExternalLink/></a></div></section>}
function Title({small,title,text}){return <div className="title"><small>{small}</small><h1>{title}</h1><p>{text}</p></div>}
function Payment({amount,payload,back}){const copy=v=>navigator.clipboard?.writeText(v);return <div className="payment"><div className="payhead"><Landmark/><div><small>PAGAMENTO VIA PIX</small><h2>Dados para pagamento</h2></div></div><div className="payamount"><span>VALOR</span><strong>R$ {Number(amount).toFixed(2).replace('.',',')}</strong></div><div className="qrbox"><QRCodeSVG value={payload} size={190}/></div><p className="scan">Escaneie pelo aplicativo da sua instituição financeira ou utilize o PIX Copia e Cola.</p><div className="copybox"><small>PIX COPIA E COLA</small><code>{payload}</code><button onClick={()=>copy(payload)}><Copy/> COPIAR CÓDIGO PIX</button></div><div className="receiver"><div><Building2/><span><small>RECEBEDOR</small><b>{RECEIVER}</b></span></div><div><Landmark/><span><small>INSTITUIÇÃO</small><b>Nubank</b></span></div><div><MapPin/><span><small>CIDADE</small><b>Bauru — SP</b></span></div></div><div className="keyline"><span><small>CHAVE PIX</small><b>{PIX_KEY}</b></span><button onClick={()=>copy(PIX_KEY)}><Copy/></button></div><div className="notice"><ShieldCheck/><p><b>Confirmação de pagamento</b><br/>Até a integração bancária ser ativada, a confirmação é feita após conferência financeira da HOCCO.</p></div><button className="secondary" onClick={back}>ALTERAR VALOR</button></div>}