import crypto from 'node:crypto';
import postgres from 'postgres';
import { isAdmin } from './_doox-v2-auth.js';
const BUCKET='doox-v2-arquivos';
const SUPABASE_URL=String(process.env.SUPABASE_URL||'https://txbowobtfiiqqatqjfpd.supabase.co').replace(/\/$/,'');
const SERVICE_ROLE_KEY=String(process.env.SUPABASE_SERVICE_ROLE_KEY||'');
const DATABASE_URL=String(process.env.DOOX_DATABASE_URL||'');
const LIMITS={LOGO:5*1024*1024,AUDIO:15*1024*1024,IMAGEM:10*1024*1024,OUTRO:10*1024*1024};
const MIME={LOGO:['image/jpeg','image/png','image/webp'],AUDIO:['audio/mpeg','audio/mp3','audio/wav','audio/x-wav','audio/wave'],IMAGEM:['image/jpeg','image/png','image/webp'],OUTRO:[]};
function json(res,status,body){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(body));}
function clean(v){return String(v??'').trim();}
function safeName(n){return(clean(n).split(/[\\/]/).pop()||'arquivo').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/-+/g,'-').replace(/^[-.]+|[-.]+$/g,'').slice(0,120)||'arquivo';}
function ext(name,mime){const r=clean(name).split('.').pop()?.toLowerCase();if(r&&r!==clean(name).toLowerCase())return r.replace(/[^a-z0-9]/g,'').slice(0,8)||'bin';return({'image/jpeg':'jpg','image/png':'png','image/webp':'webp','audio/mpeg':'mp3','audio/mp3':'mp3','audio/wav':'wav','audio/x-wav':'wav','audio/wave':'wav'})[mime]||'bin';}
function secret(){const s=String(process.env.DOOX_TRACKING_SECRET||process.env.DOOX_ADMIN_SECRET||process.env.DOOX_ADMIN_SESSION_SECRET||'').trim();if(s)return s;if(DATABASE_URL)return crypto.createHash('sha256').update(`doox-v2:${DATABASE_URL}`).digest('hex');throw new Error('Acompanhamento não configurado.');}
function verify(token){const [enc,sig]=clean(token).split('.');if(!enc||!sig)throw new Error('Token de acompanhamento inválido.');const payload=Buffer.from(enc,'base64url').toString('utf8');const expected=crypto.createHmac('sha256',secret()).update(payload).digest('base64url');const a=Buffer.from(sig),b=Buffer.from(expected);if(a.length!==b.length||!crypto.timingSafeEqual(a,b))throw new Error('Token de acompanhamento inválido.');const [id,exp]=payload.split('.');if(!id||Date.now()>Number(exp))throw new Error('Token de acompanhamento expirado.');return id;}
function validate(type,mime,size){if(!(type in LIMITS))throw new Error('Tipo de material inválido.');if(!Number.isFinite(size)||size<=0)throw new Error('Tamanho do material inválido.');if(size>LIMITS[type])throw new Error(`Arquivo excede o limite permitido para ${type}.`);if(MIME[type].length&&!MIME[type].includes(mime))throw new Error(`Formato não permitido para ${type}.`);}
function config(){if(!SUPABASE_URL||!SERVICE_ROLE_KEY)throw new Error('Storage não configurado.');if(!DATABASE_URL)throw new Error('Banco não configurado.');}
function objectUrl(path){return `${SUPABASE_URL}/storage/v1/object/${BUCKET}/${path.split('/').map(encodeURIComponent).join('/')}`;}
async function signedUpload(path){const r=await fetch(`${SUPABASE_URL}/storage/v1/object/upload/sign/${BUCKET}/${path.split('/').map(encodeURIComponent).join('/')}`,{method:'POST',headers:{Authorization:`Bearer ${SERVICE_ROLE_KEY}`,apikey:SERVICE_ROLE_KEY,'Content-Type':'application/json'},body:JSON.stringify({upsert:false})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||d.error||`Falha ao preparar upload (${r.status}).`);const s=d.signedUrl||d.signedURL||d.url;if(!s)throw new Error('Storage não retornou URL de upload.');return String(s).startsWith('http')?s:`${SUPABASE_URL}/storage/v1${s}`;}
async function objectInfo(path){const r=await fetch(objectUrl(path),{method:'HEAD',headers:{Authorization:`Bearer ${SERVICE_ROLE_KEY}`,apikey:SERVICE_ROLE_KEY}});if(!r.ok)throw new Error(`Arquivo não encontrado no Storage (${r.status}).`);return{size:Number(r.headers.get('content-length')||0),mime:clean(r.headers.get('content-type')).toLowerCase()};}
async function signedDownload(path){const r=await fetch(`${SUPABASE_URL}/storage/v1/object/sign/${BUCKET}/${path.split('/').map(encodeURIComponent).join('/')}`,{method:'POST',headers:{Authorization:`Bearer ${SERVICE_ROLE_KEY}`,apikey:SERVICE_ROLE_KEY,'Content-Type':'application/json'},body:JSON.stringify({expiresIn:3600})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||d.error||`Falha ao gerar download (${r.status}).`);const u=d.signedURL||d.signedUrl||d.path;if(!u)throw new Error('Storage não retornou o link assinado.');return String(u).startsWith('http')?u:`${SUPABASE_URL}/storage/v1${u}`;}
async function register(id,type,name,mime,size,path){const sql=postgres(DATABASE_URL,{ssl:'require',prepare:false,max:1,idle_timeout:10,connect_timeout:10});try{const rows=await sql`select doox_v2.registrar_material(${id}::uuid,${type},${name},${mime},${Number(size)},${path},${null}) as data`;return rows?.[0]?.data||null;}finally{await sql.end({timeout:5}).catch(()=>{});}}
function bodyOf(req){if(req.body&&typeof req.body==='object')return req.body;try{return req.body?JSON.parse(req.body):{};}catch{return{};}}
export default async function handler(req,res){
  try{config();const body=bodyOf(req);const action=clean(req.query?.action||body.action).toLowerCase();
    if(req.method==='GET'&&action==='download_url'){if(!isAdmin(req))return json(res,401,{ok:false,message:'Autorização administrativa necessária.'});const path=clean(req.query?.path);if(!path)throw new Error('Caminho de armazenamento inválido.');return json(res,200,{ok:true,download_url:await signedDownload(path),expires_in:3600});}
    if(req.method!=='POST')return json(res,405,{ok:false,message:'Método não permitido.'});const id=clean(body.pedidoId||body.technicalId||body.pedido_id);if(!/^[0-9a-f-]{36}$/i.test(id))throw new Error('Identificador técnico do pedido inválido.');if(verify(body.trackingToken||body.token)!==id)throw new Error('Token não corresponde ao pedido.');
    if(action==='prepare_upload'){const type=clean(body.materialType||body.tipo||body.type).toUpperCase(),name=clean(body.fileName||body.originalName||'arquivo'),mime=clean(body.mimeType||body.mime||'application/octet-stream').toLowerCase(),size=Number(body.size||0);validate(type,mime,size);const file=`${crypto.randomUUID()}-${safeName(name).replace(/\.[^.]+$/,'')}.${ext(name,mime)}`,path=`pedidos/${id}/${type}/${file}`;return json(res,200,{ok:true,upload:{pedido_id:id,tipo:type,nome_original:name,mime_type:mime,tamanho_bytes:size,storage_path:path,signed_url:await signedUpload(path),expires_in:7200}});}
    if(action==='register'){const type=clean(body.materialType||body.tipo||body.type).toUpperCase(),name=clean(body.fileName||body.originalName||'arquivo'),mime=clean(body.mimeType||body.mime||'application/octet-stream').toLowerCase(),size=Number(body.size||0),path=clean(body.storagePath||body.path);if(!path.startsWith(`pedidos/${id}/`))throw new Error('Caminho de armazenamento inválido.');validate(type,mime,size);const info=await objectInfo(path);if(info.size&&info.size!==size)throw new Error('O tamanho do arquivo armazenado não corresponde ao informado.');const data=await register(id,type,name,mime,size,path);return json(res,200,{ok:true,material:{id:data?.id||null,pedido_id:id,tipo:type,nome_original:name,mime_type:mime,tamanho_bytes:size,storage_path:path,registrado:true,status_material:data?.status_material||'RECEBIDO'}});}
    return json(res,400,{ok:false,message:'Ação de materiais inválida.'});
  }catch(e){console.error('DOOX V2 materials',e);const raw=String(e?.message||'');const allowed=[/Tipo de material/i,/Tamanho do material/i,/Arquivo excede/i,/Formato não permitido/i,/Caminho de armazenamento/i,/Token/i,/Identificador técnico/i,/tamanho do arquivo armazenado/i];return json(res,400,{ok:false,message:allowed.some(r=>r.test(raw))?raw:'Não foi possível concluir o envio do material agora.'});}
}
